/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { Kyc } from "./Kyc";

export class KycFactory {
  static connect(address: string, signerOrProvider: Signer | Provider): Kyc {
    return new Contract(address, _abi, signerOrProvider) as Kyc;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_wallet",
        type: "address"
      }
    ],
    name: "getIdentityByAddress",
    outputs: [
      {
        internalType: "bytes32",
        name: "username",
        type: "bytes32"
      },
      {
        internalType: "address",
        name: "owner",
        type: "address"
      },
      {
        internalType: "bytes32",
        name: "kycApprovedDetailsIPFS",
        type: "bytes32"
      },
      {
        internalType: "bytes32",
        name: "profileDetailsIPFS",
        type: "bytes32"
      },
      {
        internalType: "enum IKycDapp.KYC_STATUS",
        name: "level1",
        type: "uint8"
      },
      {
        internalType: "enum IKycDapp.KYC_STATUS",
        name: "level3",
        type: "uint8"
      },
      {
        internalType: "enum IKycDapp.KYC_STATUS",
        name: "level4",
        type: "uint8"
      },
      {
        internalType: "enum IKycDapp.KYC_STATUS",
        name: "level5",
        type: "uint8"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_username",
        type: "bytes32"
      }
    ],
    name: "getIdentityByUsername",
    outputs: [
      {
        internalType: "bytes32",
        name: "username",
        type: "bytes32"
      },
      {
        internalType: "address",
        name: "owner",
        type: "address"
      },
      {
        internalType: "bytes32",
        name: "kycApprovedDetailsIPFS",
        type: "bytes32"
      },
      {
        internalType: "bytes32",
        name: "profileDetailsIPFS",
        type: "bytes32"
      },
      {
        internalType: "enum IKycDapp.KYC_STATUS",
        name: "level1",
        type: "uint8"
      },
      {
        internalType: "enum IKycDapp.KYC_STATUS",
        name: "level3",
        type: "uint8"
      },
      {
        internalType: "enum IKycDapp.KYC_STATUS",
        name: "level4",
        type: "uint8"
      },
      {
        internalType: "enum IKycDapp.KYC_STATUS",
        name: "level5",
        type: "uint8"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wallet",
        type: "address"
      },
      {
        internalType: "address",
        name: "_platform",
        type: "address"
      }
    ],
    name: "getKycLevel2",
    outputs: [
      {
        internalType: "enum IKycDapp.KYC_STATUS",
        name: "",
        type: "uint8"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wallet",
        type: "address"
      }
    ],
    name: "isKycLevel1",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wallet",
        type: "address"
      },
      {
        internalType: "address",
        name: "_platform",
        type: "address"
      }
    ],
    name: "isKycLevel2",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wallet",
        type: "address"
      }
    ],
    name: "isKycLevel3",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wallet",
        type: "address"
      }
    ],
    name: "isKycLevel4",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wallet",
        type: "address"
      }
    ],
    name: "isKycLevel5",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_username",
        type: "bytes32"
      }
    ],
    name: "resolveAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    stateMutability: "view",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wallet",
        type: "address"
      }
    ],
    name: "resolveUsername",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
